### ISSUE TITLE
Matter Cannon Crashing a Server

### ISSUE THREAD

**Issue by RocketWombat** [AllTheMods/SLOP2-slice-of-pie-2#4] opened 2021-02-21 04:34 UTC
Fired a matter cannon with lead bullets in it and it crashed the server

Here is the crash report:
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 2/21/21 4:25 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.entity.Entity.func_184215_y(Lnet/minecraft/entity/Entity;)Z
	at appeng.items.tools.powered.MatterCannonItem.standardAmmo(MatterCannonItem.java:304) ~[appliedenergistics2:8.2.0-beta.2] {re:classloading,pl:runtimedistcleaner:A}
	at appeng.items.tools.powered.MatterCannonItem.func_77659_a(MatterCannonItem.java:164) ~[appliedenergistics2:8.2.0-beta.2] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:214) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:forge:filled_map.4,pl:mixin:APP:dankstorage.mixins.json:ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:287) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:PlayerInteractionManagerMixin,pl:mixin:A}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147346_a(ServerPlayNetHandler.java:982) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:ServerPlayNetHandlerPlayerSpeedLimitsMixin,pl:mixin:APP:randompatches.mixins.json:timeouts.ServerPlayNetHandlerKeepAliveMixin,pl:mixin:A}
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:31) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:9) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 4.4.0-201-generic
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4206886872 bytes (4011 MB) / 6291456000 bytes (6000 MB) up to 6291456000 bytes (6000 MB)
	CPUs: 16
	JVM Flags: 20 total; -Xms6000M -Xmx6000M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.0.10.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.10.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.0.10.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.10.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.0.10.jar fml TRANSFORMATIONSERVICE 
	FML: 36.0
	Forge: net.minecraftforge:36.0.10
	FML Language Providers: 
		javafml@36.0
		minecraft@1
	Mod List: 
		rhino-1.7.13-build.14.jar                         |Rhino                         |rhino                         |1.7.13-build.14     |DONE      |NOSIGNATURE
		ftb-essentials-1604.1.0.13.jar                    |FTB Essentials                |ftbessentials                 |1604.1.0.13         |DONE      |NOSIGNATURE
		biggerreactors-1.16.4-0.4.3.jar                   |Bigger Reactors               |biggerreactors                |0.4.3               |DONE      |NOSIGNATURE
		Cucumber-1.16.4-4.1.6.jar                         |Cucumber Library              |cucumber                      |4.1.6               |DONE      |NOSIGNATURE
		pamhc2trees-1.16.3-1.0.0.jar                      |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.0               |DONE      |NOSIGNATURE
		woot-1.16.4-1.0.3.0.jar                           |Woot                          |woot                          |1.16.4-1.0.3.0      |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.66.jar                           |Just Enough Items             |jei                           |7.6.1.66            |DONE      |NOSIGNATURE
		metalbarrels-3.3a.jar                             |Metal Barrels                 |metalbarrels                  |3.3a                |DONE      |NOSIGNATURE
		AttributeFix-1.16.5-10.0.1.jar                    |AttributeFix                  |attributefix                  |10.0.1              |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Mekanism-1.16.4-10.0.19.446.jar                   |Mekanism                      |mekanism                      |10.0.19             |DONE      |NOSIGNATURE
		bambooeverything-1.16.3-forge-1.0.0.jar           |Bamboo Everything             |bambooeverything              |1.16.3-forge-1.0.0  |DONE      |NOSIGNATURE
		ae2extras-1.2-1.16.4.jar                          |AE2 Extras                    |ae2extras                     |1.2-1.16.4          |DONE      |NOSIGNATURE
		invtweaks-1.16.4-1.0.1.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |DONE      |NOSIGNATURE
		create-mc1.16.3_v0.3e.jar                         |Create                        |create                        |mc1.16.3_v0.3e      |DONE      |NOSIGNATURE
		Clumps-6.0.0.13.jar                               |Clumps                        |clumps                        |6.0.0.13            |DONE      |NOSIGNATURE
		CookingForBlockheads_1.16.3-9.2.2.jar             |Cooking for Blockheads        |cookingforblockheads          |9.2.2               |DONE      |NOSIGNATURE
		Placebo-1.16.4-4.4.1.jar                          |Placebo                       |placebo                       |4.4.1               |DONE      |NOSIGNATURE
		dankstorage-3.14.jar                              |Dank Storage                  |dankstorage                   |3.14                |DONE      |NOSIGNATURE
		appliedenergistics2-8.2.0-beta.2.jar              |Applied Energistics 2         |appliedenergistics2           |8.2.0-beta.2        |DONE      |95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		[1.16.4]-additionalbars-1.6.0.jar                 |Additional Bars               |additionalbars                |1.6.0               |DONE      |NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.89-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.89     |DONE      |NOSIGNATURE
		phosphophyllite-1.16.4-0.4.1.jar                  |Phosphophyllite               |phosphophyllite               |0.4.1               |DONE      |NOSIGNATURE
		engineerstools-1.16.4-1.1.4.jar                   |Engineer's Tools              |engineerstools                |1.1.4               |DONE      |bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		reliquary-1.16.3-1.3.4.1061.jar                   |Reliquary                     |xreliquary                    |1.16.3-1.3.4.1061   |DONE      |NOSIGNATURE
		randompatches-2.4.0-forge.jar                     |RandomPatches                 |randompatches                 |2.4.0-forge         |DONE      |92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		Morpheus-1.16.4-4.2.68.jar                        |Morpheus                      |morpheus                      |4.2.68              |DONE      |NOSIGNATURE
		MekanismGenerators-1.16.4-10.0.19.446.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.19             |DONE      |NOSIGNATURE
		forge-1.16.5-36.0.10-universal.jar                |Forge                         |forge                         |36.0.10             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		BloodMagic-1.16.4-3.1.0-15.jar                    |Blood Magic                   |bloodmagic                    |1.16.4-3.1.0-15     |DONE      |NOSIGNATURE
		absentbydesign-1.16.4-1.3.2.jar                   |Absent By Design Mod          |absentbydesign                |1.16.4-1.3.2        |DONE      |1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		MysticalAgriculture-1.16.4-4.1.4.jar              |Mystical Agriculture          |mysticalagriculture           |4.1.4               |DONE      |NOSIGNATURE
		MysticalAgradditions-1.16.4-4.1.3.jar             |Mystical Agradditions         |mysticalagradditions          |4.1.3               |DONE      |NOSIGNATURE
		alltheores-1.1.20-1.16.4-35.1.13.jar              |AllTheOres                    |alltheores                    |1.1.20-1.16.4-35.1.1|DONE      |NOSIGNATURE
		chocolate-1.3.0-1.16.4.jar                        |Chocolate                     |chocolate                     |1.3.0-1.16.4        |DONE      |NOSIGNATURE
		forge-1.16.5-36.0.10-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		cofh_core-1.16.3-1.1.6.jar                        |CoFH Core                     |cofh_core                     |1.1.6               |DONE      |NOSIGNATURE
		thermal_foundation-1.16.3-1.1.6.jar               |Thermal Series                |thermal                       |1.1.6               |DONE      |NOSIGNATURE
		industrial-foregoing-1.16.5-3.2.9.1-fbef27c.jar   |Industrial Foregoing          |industrialforegoing           |3.2.9.1             |DONE      |NOSIGNATURE
		useful_backpacks-1.16.4-1.11.6.87.jar             |Useful Backpacks              |usefulbackpacks               |1.11.6.87           |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		torchmaster-2.3.6.jar                             |Torchmaster                   |torchmaster                   |2.3.6               |DONE      |NOSIGNATURE
		resourcefulbees-1.16.5-0.5.9_3b.jar               |Resourceful Bees              |resourcefulbees               |1.16.5-0.5.9_3b     |DONE      |NOSIGNATURE
		repurposed_structures-1.16.4-2.3.4.jar            |Repurposed Structures         |repurposed_structures         |1.16.4-2.3.4        |DONE      |NOSIGNATURE
		theoneprobe-1.16-3.0.7.jar                        |The One Probe                 |theoneprobe                   |1.16-3.0.7          |DONE      |NOSIGNATURE
		thermal_innovation-1.16.3-1.1.7.jar               |Thermal Innovation            |thermal_innovation            |1.1.7               |DONE      |NOSIGNATURE
		titanium-1.16.4-3.2.5.jar                         |Titanium                      |titanium                      |3.2.5               |DONE      |NOSIGNATURE
		SilentLib-1.16.3-4.9.1+64.jar                     |Silent Lib                    |silentlib                     |4.9.1+64            |DONE      |NOSIGNATURE
		BiomesOPlenty-1.16.4-13.0.0.431-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.431   |DONE      |NOSIGNATURE
		MekanismAdditions-1.16.4-10.0.19.446.jar          |Mekanism: Additions           |mekanismadditions             |10.0.19             |DONE      |NOSIGNATURE
		valkyrielib-1.16.5-3.0.7.1.jar                    |ValkyrieLib                   |valkyrielib                   |1.16.5-3.0.7.1      |DONE      |NOSIGNATURE
		envirocore-1.16.5-3.0.7.1.jar                     |Environmental Core            |envirocore                    |1.16.5-3.0.7.1      |DONE      |NOSIGNATURE
		envirotech-1.16.5-3.0.7.1.jar                     |Environmental Tech            |envirotech                    |3.0.7.1             |DONE      |NOSIGNATURE
		enviromats-1.16.5-2.0.7.0.jar                     |Environmental Materials       |enviromats                    |2.0.7.0             |DONE      |NOSIGNATURE
		pamhc2crops-1.16.3-1.0.1.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |DONE      |NOSIGNATURE
		SilentGear-1.16.3-2.5.5+213.jar                   |Silent Gear                   |silentgear                    |2.5.5+213           |DONE      |NOSIGNATURE
		Botania-1.16.4-411.jar                            |Botania                       |botania                       |1.16.4-411          |DONE      |NOSIGNATURE
		pamhc2foodextended-1.16.3-1.0.1.jar               |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |DONE      |NOSIGNATURE
		enviroenergy-1.16.5-3.0.7.0.jar                   |Environmental Energy          |enviroenergy                  |3.0.7.0             |DONE      |NOSIGNATURE
		curios-forge-1.16.5-4.0.4.0.jar                   |Curios API                    |curios                        |1.16.5-4.0.4.0      |DONE      |NOSIGNATURE
		Patchouli-1.16.4-48.jar                           |Patchouli                     |patchouli                     |1.16.4-48           |DONE      |NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.2.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |DONE      |NOSIGNATURE
		ftb-backups-2.1.1.6.jar                           |FTB Backups                   |ftbbackups                    |2.1.1.6             |DONE      |NOSIGNATURE
		thermal_cultivation-1.16.3-1.1.6.jar              |Thermal Cultivation           |thermal_cultivation           |1.1.6               |DONE      |NOSIGNATURE
		FastWorkbench-1.16.4-4.5.0.jar                    |FastWorkbench                 |fastbench                     |4.5.0               |DONE      |NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
		StorageDrawers-1.16.3-8.2.2.jar                   |Storage Drawers               |storagedrawers                |8.2.2               |DONE      |NOSIGNATURE
		thermal_expansion-1.16.3-1.1.6.jar                |Thermal Expansion             |thermal_expansion             |1.1.6               |DONE      |NOSIGNATURE
		DrawersTooltip-1.16.2-2.1.0.jar                   |Drawers Tooltip               |drawerstooltip                |2.1.0               |DONE      |NOSIGNATURE
		ftb-ultimine-1603.1.1.13.jar                      |FTB Ultimine                  |ftbultimine                   |1603.1.1.13         |DONE      |NOSIGNATURE
		tombstone-1.16-6.3.0.jar                          |Corail Tombstone              |tombstone                     |1.16-6.3.0          |DONE      |NOSIGNATURE
		Quark-r2.4-303.jar                                |Quark                         |quark                         |r2.4-303            |DONE      |NOSIGNATURE
		MekanismTools-1.16.4-10.0.19.446.jar              |Mekanism: Tools               |mekanismtools                 |10.0.19             |DONE      |NOSIGNATURE
		FastFurnace-1.16.4-4.4.0.jar                      |FastFurnace                   |fastfurnace                   |4.4.0               |DONE      |NOSIGNATURE
		constructionwand-1.16.2-1.7.jar                   |Construction Wand             |constructionwand              |1.16.2-1.7          |DONE      |NOSIGNATURE
		architectury-1.5.107-forge.jar                    |Architectury                  |architectury                  |1.5.107             |DONE      |NOSIGNATURE
		ftb-gui-library-1605.2.1.39-forge.jar             |FTB GUI Library               |ftbguilibrary                 |1605.2.1.39         |DONE      |NOSIGNATURE
		ftb-teams-1604.1.0.15-forge.jar                   |FTB Teams                     |ftbteams                      |1604.1.0.15         |DONE      |NOSIGNATURE
		ftb-chunks-1604.2.2.62.jar                        |FTB Chunks                    |ftbchunks                     |1604.2.2.62         |DONE      |NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		engineersdecor-1.16.4-1.1.7.jar                   |Engineer's Decor              |engineersdecor                |1.1.7               |DONE      |bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		AI-Improvements-1.16.2-0.3.0.jar                  |AI-Improvements               |aiimprovements                |0.3.0               |DONE      |NOSIGNATURE
		allthetweaks-1.2.6-1.16.4-35.1.13.jar             |All The Tweaks                |allthetweaks                  |1.2.6-1.16.4-35.1.13|DONE      |NOSIGNATURE
		kubejs-1605.3.6-build.162-forge.jar               |KubeJS                        |kubejs                        |1605.3.6-build.162  |DONE      |NOSIGNATURE
		kubejs-mekanism-1604.1.1.6.jar                    |KubeJS Mekanism               |kubejs_mekanism               |1604.1.1.6          |DONE      |NOSIGNATURE
		kubejs-thermal-1604.1.0.5.jar                     |KubeJS Thermal                |kubejs_thermal                |1604.1.0.5          |DONE      |NOSIGNATURE
		u_team_core-1.16.4-3.1.17.192.jar                 |U Team Core                   |uteamcore                     |3.1.17.192          |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		trashcans-1.0.7-mc1.16.4.jar                      |Trash Cans                    |trashcans                     |1.0.7               |DONE      |NOSIGNATURE
		byg-1.1.9.jar                                     |Oh The Biomes You'll Go       |byg                           |1.1.9               |DONE      |NOSIGNATURE
		bwncr-1.16.4-3.9.16.jar                           |Bad Wither No Cookie Reloaded |bwncr                         |1.16.4-3.9.16       |DONE      |NOSIGNATURE
		CobbleForDays-1.3.1.jar                           |Cobble For Days               |cobblefordays                 |1.3.1               |DONE      |NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |DONE      |NOSIGNATURE
		CosmeticArmorReworked-1.16.5-v1a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v1a          |DONE      |5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		geckolib-forge-1.16.5-3.0.12.jar                  |GeckoLib                      |geckolib3                     |3.0.12              |DONE      |NOSIGNATURE
		ars_nouveau-1.16.4-1.11.4.jar                     |Ars Nouveau                   |ars_nouveau                   |1.11.4              |DONE      |NOSIGNATURE
	Crash Report UUID: f1a229a4-dc59-4a2f-a7e6-be2e82a95833
	Player Count: 2 / 20; [ServerPlayerEntity['Jdrs132'/375, l='ServerLevel[world]', x=-1429.86, y=63.00, z=-1662.41], ServerPlayerEntity['mceggersonJr'/619, l='ServerLevel[world]', x=-1402.27, y=125.00, z=-1691.80]]
	Data Packs: resourcefulbees:internals, vanilla, mod:rhino, mod:ftbessentials, mod:biggerreactors, mod:cucumber, mod:pamhc2trees (incompatible), mod:woot, mod:jei, mod:metalbarrels (incompatible), mod:attributefix, mod:mekanism, mod:bambooeverything (incompatible), mod:ae2extras (incompatible), mod:invtweaks (incompatible), mod:create (incompatible), mod:clumps, mod:cookingforblockheads (incompatible), mod:placebo (incompatible), mod:dankstorage, mod:appliedenergistics2 (incompatible), mod:additionalbars, mod:sereneseasons, mod:phosphophyllite, mod:engineerstools, mod:xreliquary, mod:randompatches, mod:morpheus (incompatible), mod:mekanismgenerators, mod:forge, mod:bloodmagic, mod:absentbydesign (incompatible), mod:mysticalagriculture, mod:mysticalagradditions (incompatible), mod:alltheores, mod:chocolate, mod:cofh_core (incompatible), mod:thermal (incompatible), mod:industrialforegoing (incompatible), mod:usefulbackpacks, mod:torchmaster (incompatible), mod:resourcefulbees (incompatible), mod:repurposed_structures, mod:theoneprobe, mod:thermal_innovation (incompatible), mod:titanium (incompatible), mod:silentlib (incompatible), mod:biomesoplenty, mod:mekanismadditions, mod:valkyrielib, mod:envirocore (incompatible), mod:envirotech, mod:enviromats (incompatible), mod:pamhc2crops (incompatible), mod:silentgear, mod:botania, mod:pamhc2foodextended (incompatible), mod:enviroenergy, mod:curios, mod:patchouli (incompatible), mod:pamhc2foodcore (incompatible), mod:ftbbackups (incompatible), mod:thermal_cultivation (incompatible), mod:fastbench (incompatible), mod:autoreglib (incompatible), mod:storagedrawers (incompatible), mod:thermal_expansion (incompatible), mod:drawerstooltip, mod:ftbultimine (incompatible), mod:tombstone, mod:quark (incompatible), mod:mekanismtools, mod:fastfurnace (incompatible), mod:constructionwand (incompatible), mod:architectury, mod:ftbguilibrary (incompatible), mod:ftbteams (incompatible), mod:ftbchunks (incompatible), mod:appleskin, mod:engineersdecor, mod:aiimprovements, mod:allthetweaks, mod:kubejs, mod:kubejs_mekanism, mod:kubejs_thermal, mod:uteamcore, mod:trashcans, mod:byg, mod:bwncr (incompatible), mod:cobblefordays (incompatible), mod:fastleafdecay (incompatible), mod:cosmeticarmorreworked (incompatible), mod:geckolib3 (incompatible), mod:ars_nouveau
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by MadWomen** [comment] 2021-02-24 05:21
SLOP 2 just had an update, you could see if the issue is resolved in the latest version.

**Closed as completed** 2021-04-18 00:06 UTC
